# Site settings
name: Xuanrong Pang
location: 深圳
company: IBM
position: Java开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "D:/pangxuanrong.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

